use std::collections::HashMap;

use serde::Serialize;

#[cfg(target_arch = "wasm32")]
use zela_std::rpc_client::RpcClient;
#[cfg(not(target_arch = "wasm32"))]
use solana_client::nonblocking::rpc_client::RpcClient;

// ---------------------------------------------------------------------------
// Embedded precomputed map
// ---------------------------------------------------------------------------

/// Precomputed CSV: pubkey,country,region — generated by scripts/precompute_regions.py.
/// Embedded at compile time so the procedure carries no runtime geo dependencies.
const VALIDATOR_REGIONS: &str = include_str!("../data/validator_regions.csv");

// ---------------------------------------------------------------------------
// Region type
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy)]
enum Region {
    Frankfurt,
    Dubai,
    NewYork,
    Tokyo,
}

impl Region {
    fn as_str(self) -> &'static str {
        match self {
            Self::Frankfurt => "Frankfurt",
            Self::Dubai => "Dubai",
            Self::NewYork => "NewYork",
            Self::Tokyo => "Tokyo",
        }
    }

    fn parse(s: &str) -> Option<Self> {
        match s.trim() {
            "Frankfurt" => Some(Self::Frankfurt),
            "Dubai" => Some(Self::Dubai),
            "NewYork" => Some(Self::NewYork),
            "Tokyo" => Some(Self::Tokyo),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Geo helpers
// ---------------------------------------------------------------------------

/// Parses the embedded CSV into a {pubkey → (country_code, region)} map.
fn build_region_map() -> HashMap<String, (String, Region)> {
    VALIDATOR_REGIONS
        .lines()
        .skip(1) // skip header row
        .filter_map(|line| {
            let mut cols = line.splitn(3, ',');
            let pubkey = cols.next()?;
            let country = cols.next()?;
            let region = Region::parse(cols.next()?)?;
            Some((pubkey.to_string(), (country.to_string(), region)))
        })
        .collect()
}

/// Coarse IP → region mapping based on Regional Internet Registry (RIR) first-octet ranges.
/// Used only when a validator is absent from the precomputed map.
/// Accuracy is intentionally low — this is a last-resort fallback.
fn ip_to_region(ip: &str) -> Option<Region> {
    let first: u8 = ip.split('.').next()?.parse().ok()?;
    Some(match first {
        // APNIC (Asia-Pacific) → Tokyo
        1 | 14 | 27 | 36 | 39 | 42 | 43 | 49 | 58..=61
        | 101 | 103 | 110..=126 | 175 | 180 | 182 | 183
        | 202 | 203 | 210 | 211 | 218..=223 => Region::Tokyo,

        // RIPE NCC (Europe + Middle East + Central Asia) → Frankfurt
        2 | 5 | 31 | 37 | 46 | 62 | 77..=95
        | 176 | 178 | 185 | 188 | 193..=195 | 212 | 213 | 217 => Region::Frankfurt,

        // LACNIC (Latin America) → NewYork
        177 | 179 | 181 | 186 | 187 | 189..=191 | 200 | 201 => Region::NewYork,

        // AFRINIC (Africa) → Dubai
        41 | 102 | 105 | 154 | 196 | 197 => Region::Dubai,

        // ARIN + everything else (mostly North America / cloud) → NewYork
        _ => Region::NewYork,
    })
}

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------

#[derive(Serialize)]
pub struct Output {
    /// Current Solana slot.
    pub slot: u64,
    /// Identity pubkey of the current slot leader.
    pub leader: String,
    /// Coarse geographic location of the leader.
    /// ISO 3166-1 alpha-2 country code when from the precomputed map (e.g. "DE").
    /// "UNKNOWN" when the leader could not be geolocated.
    pub leader_geo: String,
    /// Nearest Zela server region: Frankfurt | Dubai | NewYork | Tokyo.
    /// Defaults to "Frankfurt" when leader_geo is "UNKNOWN".
    pub closest_region: String,
}

// ---------------------------------------------------------------------------
// Core procedure logic (target-independent)
// ---------------------------------------------------------------------------

pub struct LeaderRouting;

impl LeaderRouting {
    pub async fn run(rpc: &RpcClient) -> Result<Output, String> {
        // 1. Current slot.
        let slot = rpc.get_slot().await.map_err(|e| e.to_string())?;
        log::info!("slot={slot}");

        // 2. Slot leader.
        let leaders = rpc
            .get_slot_leaders(slot, 1)
            .await
            .map_err(|e| format!("get_slot_leaders(slot={slot}): {e}"))?;
        let leader = leaders
            .into_iter()
            .next()
            .ok_or_else(|| format!("no leader returned for slot {slot}"))?;
        let leader_str = leader.to_string();
        log::info!("leader={leader_str}");

        // 3. Primary lookup: precomputed pubkey → (country, region) map.
        let region_map = build_region_map();
        if let Some((country, region)) = region_map.get(&leader_str) {
            log::info!("precomputed map: {country} → {}", region.as_str());
            return Ok(Output {
                slot,
                leader: leader_str,
                leader_geo: country.clone(),
                closest_region: region.as_str().to_string(),
            });
        }

        // 4. Fallback: resolve gossip IP from cluster nodes, map coarsely by RIR.
        //    This handles validators that joined after the last map regeneration
        //    or that are online but were absent from getVoteAccounts at generation time.
        log::warn!("leader {leader_str} not in precomputed map; trying cluster node IP lookup");
        let nodes = rpc.get_cluster_nodes().await.map_err(|e| e.to_string())?;

        if let Some(node) = nodes.iter().find(|n| n.pubkey == leader_str) {
            if let Some(gossip) = &node.gossip {
                // gossip is "ip:port" — works whether the field is SocketAddr or String
                let ip_str = gossip.to_string();
                let ip = ip_str.split(':').next().unwrap_or("");
                if let Some(region) = ip_to_region(ip) {
                    log::info!("RIR fallback: {ip} → {}", region.as_str());
                    return Ok(Output {
                        slot,
                        leader: leader_str,
                        leader_geo: "UNKNOWN".to_string(),
                        closest_region: region.as_str().to_string(),
                    });
                }
            }
        }

        // 5. Final fallback: leader is offline or completely unresolvable.
        //    Default to Frankfurt — the most common region (~60% of active validators).
        log::warn!("leader {leader_str} could not be geolocated; defaulting to Frankfurt");
        Ok(Output {
            slot,
            leader: leader_str,
            leader_geo: "UNKNOWN".to_string(),
            closest_region: "Frankfurt".to_string(),
        })
    }
}

// ---------------------------------------------------------------------------
// Zela wasm32 binding
// ---------------------------------------------------------------------------

#[cfg(target_arch = "wasm32")]
mod zela {
    use zela_std::{CustomProcedure, RpcError, zela_custom_procedure};
    use zela_std::rpc_client::RpcClient;

    use super::*;

    impl CustomProcedure for LeaderRouting {
        // No inputs required — the procedure derives everything from Solana RPC.
        type Params = ();
        type ErrorData = ();
        type SuccessData = Output;

        async fn run(_: Self::Params) -> Result<Self::SuccessData, RpcError<Self::ErrorData>> {
            let rpc = RpcClient::new();
            LeaderRouting::run(&rpc).await.map_err(|message| RpcError {
                code: 1,
                message,
                data: None,
            })
        }

        const LOG_MAX_LEVEL: log::LevelFilter = log::LevelFilter::Info;
    }

    zela_custom_procedure!(LeaderRouting);
}

// ---------------------------------------------------------------------------
// Local integration test (native target only)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use solana_client::nonblocking::rpc_client::RpcClient;
    use solana_sdk::commitment_config::CommitmentConfig;

    #[tokio::test]
    async fn test_leader_routing_mainnet() {
        env_logger::builder()
            .is_test(true)
            .parse_env(env_logger::Env::new().default_filter_or("info,leader_routing=debug"))
            .init();

        let rpc = RpcClient::new_with_commitment(
            "https://api.mainnet-beta.solana.com".to_string(),
            CommitmentConfig::confirmed(),
        );

        let output = LeaderRouting::run(&rpc).await.expect("procedure failed");
        log::warn!(
            "slot={} leader={} leader_geo={} closest_region={}",
            output.slot, output.leader, output.leader_geo, output.closest_region
        );

        assert!(!output.leader.is_empty());
        assert!(!output.closest_region.is_empty());
    }
}
